<?php exit();?>
CREATE TABLE IF NOT EXISTS `c2_source` (
  `sc_idx` int(11) NOT NULL AUTO_INCREMENT,
  `sc_name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_login_refer` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `sc_login_url` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_login_action` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_uid_fld` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_uid_val` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_pwd_fld` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_pwd_val` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_list_url` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_list_method` varchar(4) COLLATE utf8_unicode_ci NOT NULL,
  `sc_list_data` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_list_exp` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_idx_url` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_idx_title` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_exps` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_spage` int(11) NOT NULL,
  `sc_epage` int(11) NOT NULL,
  `sc_enctype` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_delay` int(11) NOT NULL,
  `sc_use_origin` tinyint(4) NOT NULL DEFAULT '1',
  `sc_proxy` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_proxy_uid` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `sc_proxy_pwd` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `sc_agent` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `sc_skipstr` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `sc_nodnimg` tinyint(4) NOT NULL,
  `sc_cate` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_vrange` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `sc_overlap` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `sc_wm_use1` tinyint(4) NOT NULL,
  `sc_wm_use2` tinyint(4) NOT NULL,
  `sc_repstr` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_user_list` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_wm_pos1` int(11) NOT NULL,
  `sc_wm_pos2` int(11) NOT NULL,
  `sc_wm_padding1` int(11) NOT NULL,
  `sc_wm_padding2` int(11) NOT NULL,
  `sc_img_maxw` int(11) NOT NULL,
  `sc_img_maxh` int(11) NOT NULL,
  `sc_cmt_url` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_cmt_exp` text COLLATE utf8_unicode_ci NOT NULL,
  `sc_cmt_reverse` tinyint(4) NOT NULL,
  `sc_idx_cwriter` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_idx_cdate` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_idx_cgood` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_idx_cnogood` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_idx_ccontent` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `sc_use` tinyint(4) NOT NULL,
  `sc_step` int(11) NOT NULL,
  `board` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`sc_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='크롤링 대상 소스 목록';
